version: "3.9"

networks: 
 jmeter-net:
  driver: bridge
  ipam:
    config:
      - subnet: ${jmeter_subnet}
volumes:
  jmeter-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/jmeter-vol'


services:
  slave1:
    image: hmutyala/jmeter-distslave
    networks:
      jmeter-net:
        ipv4_address: ${jmeterip_slave1}
    volumes:
      - jmeter-vol:/mnt/jmeter
    command:
      - -n -Jclient.rmi.localport=${jmeter_clientport} -Jserver.rmi.localport={jmeter_serverport}
      - -j /mnt/jmeter/slave_${jmeterip_slave1}.logdone
  

  slave2:
    image: hmutyala/jmeter-distslave
    networks:
      jmeter-net:
        ipv4_address: ${jmeterip_slave2}
    volumes:
     - jmeter-vol:/mnt/jmeter
    command:
      -n -Jclient.rmi.localport=${jmeter_clientport} -Jserver.rmi.localport={jmeter_serverport}
  
  slave3:
    image: hmutyala/jmeter-distslave
    networks:
      jmeter-net:
        ipv4_address: ${jmeterip_slave3}
    volumes:
      - jmeter-vol:/mnt/jmeter
    command:
      -n -Jclient.rmi.localport=${jmeter_clientport} -Jserver.rmi.localport={jmeter_serverport}
 
  master:
    image: hmutyala/jmeter-distmaster
    networks:
      jmeter-net:
        ipv4_address: ${jmeterip_master}
    volumes:
      - jmeter-vol:/mnt/jmeter    
    command:
  #     -n -X --rm
  #     -Jclient.rmi.localport=7000  \      
  #     -Jserver.rmi.ssl.keystore.file=/mnt/jmeter/rmi_keystore.jks  \
  #     -R 192.168.1.11  \
  #     -t /mnt/jmeter/Distri_Test1.jmx  \
  #     -l /mnt/jmeter/master/result_$(date+%Y%m%d_%H%M%S).jtl  \
  #     -j /mnt/jmeter/master/jmeter_$(date+%Y%m%d_%H%M%S).log
    depends_on:
      - slave1
      - slave2
      - slave3
